{% set name = "clhep" %}
{% set version = "2.4.1.0" %}
{% set sha256 = "6939ea3b824bdd07e7673a969ccc983500889e1daf553277f80e3cd60fb3f022" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://proj-clhep.web.cern.ch/proj-clhep/DISTRIBUTION/tarFiles/{{ name }}-{{ version }}.tgz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - test -f ${PREFIX}/lib/libCLHEP.so  # [linux]
    - test -f ${PREFIX}/lib/libCLHEP.dylib  # [osx]
    - test -d ${PREFIX}/include/CLHEP
    - conda inspect linkages -p $PREFIX clhep  # [not win]
    - conda inspect objects -p $PREFIX clhep  # [osx]

about:
  home: http://proj-clhep.web.cern.ch/proj-clhep/
  license: LGPL-3.0
  license_family: GPL
  license_file: CLHEP/COPYING.LESSER
  summary: A Class Library for High Energy Physics
  description: |
    It is intended to be a set of HEP specific foundation and utility classes such as
    random generators, physics vectors, geometry and linear algebra.
  doc_url: http://proj-clhep.web.cern.ch/proj-clhep/index.html#docu
  dev_url: https://gitlab.cern.ch/CLHEP/CLHEP

extra:
  recipe-maintainers:
      - giacomov
