appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Jcy5peWubrc/PaBa8uLoSRh/7bJSUrA4hHgMZEEUUYxBL02EPg6Gpu2D9A3RxY3sbFTXfN35FA1ZlGEje+DI77u0ja+UCcoDEs/JoXn4E3PrfCEwyVFETsTN5KT5t/HUOb80gXzouojKO2kDNoP2J9mkNlRSLMfipIlPh362FwYTZG7COYqdGhILFtI679+YAO8HmffSOk5LPNGKcDU+W6KMCNH5dRMUuxiICMWBAtanTBj+wPNOBTe5Z6IOfUg0tNMITt/a+j18FDmuX/SHUL7dRSQFBaHWK31YVXn1RRMN6JqehbosJNDLTX8rX4YaccL863yFroW6Pv2z88phuKf+t9ZoEICoSaSUBel99gy1DhkIgpGnoREjOywRDNk7AA9DKsREJ6rzxVlwMsNmPXjc0/1Vp4y0h267wHqUnc0Z2W/wOxY8SW38+Gtf8CT+tfPsd+uf+q2+nnqa2gq08nygWz+5avZCrRLmHzahaKaLp389uMMRzXCj0+F9+hXdnxkbOdMhTpPHIOtFb0wiFkinReW3Kz4dRGiHSM2HUpTLPKmjR7EWSwV6aWr6lZQRxSwhQWDOuyAsZ6OfLxVuFe/xJE+hhRkfdLZFFV6gbWjH8m4MoziNrQyDk8dWy1GL9eA/6HNn1N50g8HT6TLsm3Vh/nchpTwVns9+yTyWy9I=}
